export const GET_ORDERS = 'GET_ORDERS';
export const GET_SELECTED_ORDER = 'GET_SELECTED_ORDER';
export const GET_NEW_ORDERS = 'GET_NEW_ORDERS';
export const GET_ORDERS_LOADING = 'GET_ORDERS_LOADING';
export const SET_ORDERS = 'GET_ORDERS';
export const SET_SELECTED_ORDER = 'GET_SELECTED_ORDER';
export const SET_NEW_ORDERS = 'GET_NEW_ORDERS';
export const SET_ORDERS_LOADING = 'GET_ORDERS_LOADING';